### ISSUE TITLE
Remove global settings?

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/collapsiblock#4]
The global settings for all blocks don't work - as we discussed here: https://github.com/backdrop-contrib/collapsiblock/issues/2#issuecomment-1198822549

Do you just want to remove those settings? 

It seems to me that in most cases this is going  to be a block by block thing, I think it's a fringe use case where someone wants to make all blocks collapsible, given that almost everything on a site is in a block.

**Comment by keiserjb** [comment]
I know taking the global settings is an option, but I fixed it so it works now.  It might be useful.

**Comment by stpaultim** [comment]
No need to remove setting, if it works. I'll close this issue.
